### ISSUE TITLE
How to install and use?

### ISSUE THREAD

**Issue by TiborUdvari** [DanielEnglisch/printer-firmware#1]
I have this printer and wanted to try this out, could you point me to some instructions of how to install and use?

**Comment by DanielEnglisch** [comment]
@TiborUdvari 
Download all files from my repository.
Open the .ino file with the Arduino IDE and upload to your printer's controller board.
It's possible that it doesn't work right away :/
For my modification I followed this guide:
https://space.planetsofa.de/?p=188
I wish you the best of luck!

**Comment by per1234** [comment]
You will have a problem if you try to follow those instructions because the Arduino IDE requires that the folder name match the .ino filename. Since this is not the case with this repository the Arduino IDE will move the .ino file to a folder with a matching name but leave behind all the other files in the original folder. So @TiborUdvari would need to change the folder name to Marlin after downloading the repository.

@DanielEnglisch I recommend you to move the files to an appropriately named subfolder (as [Marlin has done](https://github.com/MarlinFirmware/Marlin/tree/1.1.x/Marlin)) to prevent this sort of difficulty.

**Comment by DanielEnglisch** [comment]
It took some time but I finally did it. @per1234
